config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'
  get 'comments/destroy'
  get 'relationships/followings'
  get 'relationships/followers'
  root to: 'home#top'
  resources :posts do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
    member do
      get :favorites_all
    end
    collection do
      post :confirm
      get :draft
      get :index_all
      get :all_posts
      get 'search' => 'posts#search'
      get 'basic' => 'posts#basic'
      get 'stylish' => 'posts#stylish'
      get 'feminine' => 'posts#feminine'
      get 'sneaker' => 'posts#sneaker'
      get 'colorful' => 'posts#colorful'
    end
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_about.html.erb
<div class="about">
  <div class="about__text fadeUpTrigger">
    <p>WHAT’S Feesly?</p>
    <p>
      Feesly（フィースリー）は、<br>
      あしもとのコーディネートを共有するアプリです。
    </p>
    <p>
      意外と見られていないようで、実は見られているのがあしもと。<br>
      Feeslyはあなたらしいコーディネートを<br>
      見つけられる場所にしたいと思っております。
    </p>
  </div>
</div>

app/views/home/_category.html.erb
<div class="category-content">
  <%= image_tag 'caption01.png', class: "caption01" %>
  <div class="category-content__items fadeUpTrigger">
    <%= link_to basic_posts_path, class: "category-link" do %>
      <% image_tag 'category-logo_01.png', class: "category-img" %>
    <% end %>
    <%= link_to feminine_posts_path, class: "category-link" do %>
      <% image_tag 'category-logo_02.png', class: "category-img2"  %>
    <% end %>
    <%= link_to colorful_posts_path, class: "category-link" do %>
      <% image_tag 'category-logo_03.png', class: "category-img2"  %>
    <% end %>
    <%= link_to stylish_posts_path, class: "category-link" do %>
      <% image_tag 'category-logo_04.png', class: "category-img2"  %>
    <% end %>
    <%= link_to sneaker_posts_path, class: "category-link" do %>
      <% image_tag 'category-logo_05.png', class: "category-img2"  %>
    <% end %>
  </div>
  <%= image_tag 'caption02.png', class: "caption02" %>
  <% if user_signed_in? %>
    <%= link_to 'more >' , index_all_posts_path, class: "all-posts fadeUpTrigger" %>
  <% else %>
    <%= link_to 'more >' , all_posts_posts_path, class: "all-posts fadeUpTrigger" %>
  <% end %>
</div>

app/views/home/top.html.erb
<div class="main">
  <div class="main__visual">
    <div class="main__taxt">
      <p>This is so me!</p>
      <p>-足もとにも、もっとわたしらしさを-</p>
    </div>
  </div>
  <%= render 'home/about' %>
  <%= render 'home/category' %>
</div>