config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'
  get 'comments/destroy'
  get 'relationships/followings'
  get 'relationships/followers'
  root to: 'home#top'
  resources :posts do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
    member do
      get :favorites_all
    end
    collection do
      post :confirm
      get :draft
      get :index_all
      get :all_posts
      get 'search' => 'posts#search'
      get 'basic' => 'posts#basic'
      get 'stylish' => 'posts#stylish'
      get 'feminine' => 'posts#feminine'
      get 'sneaker' => 'posts#sneaker'
      get 'colorful' => 'posts#colorful'
    end
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :post_image, PostImageUploader
  validates :title, :introduction, :post_image, presence: true
  validates :title, length: { in: 1..15 }
  validates :introduction, length: { in: 1..105 }
  enum status: { published: 0, draft: 1 }

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy

  def self.search(keyword)
    where(["title like? OR  introduction like?", "%#{keyword}%", "%#{keyword}%"])
  end

  def favorited?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :login_check, {only: [:show]}
  def index
    @posts = Post.published.where(user_id: current_user.id).includes(:user).order("created_at DESC")
  end

  def index_all
    @posts = Post.published.page(params[:page]).per(5)
  end

  def all_posts
    @posts = Post.published.all
  end

  def new
    @post = Post.new
  end

  def favorites_all
    favorites = Favorite.where(user_id: current_user.id).pluck(:post_id)
    @favorite_posts = Post.find(favorites)
  end

  def confirm
    @post = Post.new(post_params)
    if @post.invalid?
      redirect_to new_post_path, alert: '入力漏れがあります。お手数ですが、入力内容をご確認のうえ再度お試しください。'
    end
  end

  def draft
    @posts = current_user.posts.draft
  end

  def create
    @post = Post.new(post_params)
    if params[:back] || !@post.save
      render :new and return

    elsif params[:post][:status] == 'draft'
      flash[:notice] = "下書き保存しました。"
      redirect_to draft_posts_path

    else params[:post][:status] == 'published'
      flash[:notice] = "投稿を完了しました。"
      redirect_to posts_path
    end
  end

  def show
    @post = Post.find(params[:id])
    @user = @post.user
    @comment = Comment.new
    @comments = @post.comments
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = "投稿内容を更新しました。"
      redirect_to posts_path
    else
      render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    flash[:notice] = "削除が完了しました。"
    redirect_to posts_path
  end

  def basic
    @posts = Post.published.where(category:"basic").page(params[:page]).per(5)
  end

  def colorful
    @posts = Post.published.where(category:"colorful").page(params[:page]).per(5)
  end

  def feminine
    @posts = Post.published.where(category:"feminine").page(params[:page]).per(5)
  end

  def sneaker
    @posts = Post.published.where(category:"sneaker").page(params[:page]).per(5)
  end

  def stylish
    @posts = Post.published.where(category:"stylish").page(params[:page]).per(5)
  end

  def post_params
    params.require(:post).permit(:title, :introduction, :post_image, :post_image_cache, :category, :status).merge(user_id: current_user.id)
  end
end

app/helpers/posts_helper.rb
module PostsHelper

  def text_placeholder
    <<-"EOS".strip_heredoc
    コーデの説明文を追加
    ※100文字以内
    ・ブランド名
    ・お値段
    ・こだわりポイント
    ・スタイルのカテゴリー
    EOS
  end
end

app/views/posts/all_posts.html.erb
<div class="index-container">
  <p class="title">すべての投稿</p>
  <div class="index-content">
    <% @posts.each do |post| %>
      <div class="index-items">
        <p><%= post.title %></p>
        <p><%= image_tag post.post_image.url, class: "index-image" %></p>
        <div class="index-nav">
          <div class="index-user">
            <% if post.user.avatar? %>
              <p><%= image_tag post.user.avatar.url, size: '50x50', class: "index-icon" %></p>
            <% else %>
              <%= image_tag 'icon_dummy.png', size: '50x50', class:"index-icon" %>
            <% end %>
            <p class="user-name"><%= post.user.name %></p>
          </div>
          <%= link_to "more", post_path(post), class: "show-link" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/basic.html.erb
<div class="index-container">
  <p class="title">ベーシック</p>
  <div class="index-content">
    <% @posts.each do |post| %>
      <div class="index-items">
        <p><%= post.title %></p>
        <p><%= image_tag post.post_image.url, class: "index-image" %></p>
        <div class="index-nav">
          <div class="index-user">
            <% if post.user.avatar? %>
              <p><%= image_tag post.user.avatar.url, size: '50x50', class: "index-icon" %></p>
            <% else %>
              <%= image_tag 'icon_dummy.png', size: '50x50', class:"index-icon" %>
            <% end %>
            <p class="user-name"><%= post.user.name %></p>
          </div>
          <%= link_to "more", post_path(post), class: "show-link" %>
        </div>
      </div>
    <% end %>
    <%= paginate(@posts) %>
  </div>
</div>

app/views/posts/colorful.html.erb
<div class="index-container">
  <p class="title">カラフル</p>
  <div class="index-content">
  <% @posts.each do |post| %>
    <div class="index-items">
      <p><%= post.title %></p>
      <p><%= image_tag post.post_image.url, class: "index-image" %></p>
      <div class="index-nav">
        <div class="index-user">
          <% if post.user.avatar? %>
            <p><%= image_tag post.user.avatar.url, size: '50x50', class: "index-icon" %></p>
          <% else %>
            <%= image_tag 'icon_dummy.png', size: '50x50', class:"index-icon" %>
          <% end %>
          <p class="user-name"><%= post.user.name %></p>
        </div>
        <%= link_to "more", post_path(post), class: "show-link" %>
      </div>
    </div>
  <% end %>
  <%= paginate(@posts) %>
</div>
</div>

app/views/posts/confirm.html.erb
<div class="container">
  <div class="container__post">
    <p class="post-title">確認画面</p>
      <div class="container__post-content">
        <div class="image">
          <%= image_tag @post.post_image.url, class: "post_image" %>
        </div>
        <div class="content">
          <p class="form-text"><%= @post.title %></p>
          <p class="form-area"><%= safe_join(@post.introduction.split("\n"),tag(:br)) %></p>
          <p class="form-area"> カテゴリー：<%= @post.category %></p>
          <%= form_with model: @post, local: true do |f| %>
            <%= f.hidden_field :post_image %>
            <%= f.hidden_field :post_image_cache %>
            <%= f.hidden_field :title %>
            <%= f.hidden_field :introduction %>
            <%= f.hidden_field :category %>
            <p class="status">ステータスを選択して完了してください。</p>
            <%= f.select :status, Post.statuses.keys.map { |k| [t("enums.post.status.#{k}"),k]}, {}, {id: 'select'}  %>
            <p><%= f.submit "完了", class:"form-btn" %></p>
            <p><%= f.submit "＜戻る", name: :back, class:"confirm-back" %></p>
          <% end %>
        </div>
      </div>
  </div
</div>

app/views/posts/draft.html.erb
<div class="index-container">
  <p class="title">下書き一覧</p>
  <div class="index-content">
    <% @posts.each do |post| %>
      <div class="index-items">
        <p><%= post.title %></p>
        <p><%= image_tag post.post_image.url, class: "index-image" %></p>
        <div class="index-links">
          <%= link_to "詳しく見る", post_url(post), class: "link" %>
          <%= link_to "編集する", edit_post_path(post), class: "link" %>
          <%= link_to "削除する", post, method: :delete, data: {confirm: "本当に削除していいですか？"}, class: "delete-link" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="container">
  <div class="container__post">
    <p class="post-title">投稿内容編集</p>
    <%= form_with model: @post, local: true do |f| %>
      <div class="container__post-content">
        <div class="image">
        <%= f.label :post_image do %>
          <% if @post.post_image.present? %>
            <%= image_tag @post.post_image.url, class: "post_image" %>
          <% else %>
            <%= image_tag 'image_upload_sample.jpg', class: "post_image" %>
          <% end %>
          <%= f.file_field :post_image, style:"display:none", class: "uploader" %>
          <%= f.hidden_field :post_image_cache %>
        <% end %>
        </div>
        <div class="content">
          <p><%= f.text_field :title, placeholder: "タイトル", class: "form-text" %></p>
          <p><%= f.text_area :introduction, placeholder: "コーデの説明文を追加する", size: '15x7', class: "form-area"  %></p>
          <div class="edit-select" >
            <p><%= f.select :category,
            [["basic(ベーシック)", "basic"],
            ["colorful(カラフル)", "colorful"],
            ["feminine(フェミニン)", "feminine"],
            ["sneaker(スニーカースタイル)", "sneaker"],
            ["stylish(スタイリッシュ)", "stylish"]],
            {include_blank: "カテゴリー選択（任意）"}, {class: 'select-edit'}  %></p>
            <%= f.select :status, Post.statuses.keys.map { |k| [t("enums.post.status.#{k}"),k]}, {}, {class: 'select-edit'}  %>
          </div>
          <p><%= f.submit "更新する", class:"form-btn" %></p>
        </div>
      </div>
    <% end %>
  </div
</div>

app/views/posts/favorites_all.html.erb
<div class="index-container">
  <p class="title">いいねした投稿</p>
  <div class="index-content">
    <% @favorite_posts.each do |post| %>
      <div class="index-items">
        <p><%= post.title %></p>
        <p><%= image_tag post.post_image.url, class: "index-image" %></p>
        <div class="index-nav">
          <div class="index-user">
            <% if post.user.avatar? %>
              <p><%= image_tag post.user.avatar.url, size: '50x50', class: "index-icon" %></p>
            <% else %>
              <%= image_tag 'icon_dummy.png', size: '50x50', class:"index-icon" %>
            <% end %>
            <p class="user-name"><%= post.user.name %></p>
            <% if post.favorited?(current_user) %>
              <%= link_to post_favorites_path(post.id), method: :delete do %>
                <% image_tag 'favo-logo-01.png', class: "favo-logo" %>
              <% end %>
            <% else %>
              <%= link_to post_favorites_path(post.id), method: :post do %>
                <% image_tag 'favo-logo-02.png', class: "favo-logo" %>
              <% end %>
            <% end %>
          </div>
          <%= link_to "more", post_path(post), class: "show-link" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/feminine.html.erb
<div class="index-container">
  <p class="title">フェミニン</p>
  <div class="index-content">
  <% @posts.each do |post| %>
    <div class="index-items">
      <p><%= post.title %></p>
      <p><%= image_tag post.post_image.url, class: "index-image" %></p>
      <div class="index-nav">
        <div class="index-user">
          <% if post.user.avatar? %>
            <p><%= image_tag post.user.avatar.url, size: '50x50', class: "index-icon" %></p>
          <% else %>
            <%= image_tag 'icon_dummy.png', size: '50x50', class:"index-icon" %>
          <% end %>
          <p class="user-name"><%= post.user.name %></p>
        </div>
        <%= link_to "more", post_path(post), class: "show-link" %>
      </div>
    </div>
  <% end %>
  <%= paginate(@posts) %>
</div>
</div>

app/views/posts/index.html.erb
<div class="index-container">
  <p class="title">自分の投稿一覧</p>
  <div class="index-content">
    <% @posts.each do |post| %>
      <div class="index-items">
        <p><%= post.title %></p>
        <p><%= image_tag post.post_image.url, class: "index-image" %></p>
        <div class="index-links">
          <%= link_to "詳しく見る", post_url(post), class: "link" %>
          <%= link_to "編集する", edit_post_path(post), class: "link" %>
          <%= link_to "削除する", post, method: :delete, data: {confirm: "本当に削除していいですか？"}, class: "delete-link" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/index_all.html.erb
<div class="index-container">
  <p class="title">みんなの投稿</p>
  <div class="index-content">
    <% @posts.each do |post| %>
      <div class="index-items">
        <p><%= post.title %></p>
        <p><%= image_tag post.post_image.url, class: "index-image" %></p>
        <div class="index-nav">
          <div class="index-user">
            <% if post.user.avatar? %>
              <p><%= image_tag post.user.avatar.url, size: '50x50', class: "index-icon" %></p>
            <% else %>
              <%= image_tag 'icon_dummy.png', size: '50x50', class:"index-icon" %>
            <% end %>
            <p class="user-name"><%= post.user.name %></p>
            <% if post.favorited?(current_user) %>
              <%= link_to post_favorites_path(post.id), method: :delete, id: "favo-delete" do %>
                <% image_tag 'favo-logo-01.png', class: "favo-logo" %>
              <% end %>
            <% else %>
              <%= link_to post_favorites_path(post.id), method: :post, id: "favo-post" do %>
                <% image_tag 'favo-logo-02.png', class: "favo-logo" %>
              <% end %>
            <% end %>
          </div>
          <%= link_to "more", post_path(post), class: "show-link" %>
        </div>
      </div>
    <% end %>
    <%= paginate(@posts) %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container">
  <div class="container__post">
    <p class="post-title">新規作成</p>
    <%= form_with model: @post, local: true, url: confirm_posts_path(@post) do |f| %>
      <div class="container__post-content">
        <div class="image">
        <%= f.label :post_image do %>
          <% if @post.post_image.present? %>
            <%= image_tag @post.post_image.url, class: "post_image" %>
          <% else %>
            <%= image_tag 'upload-image.png', class: "post_image" %>
          <% end %>
          <%= f.file_field :post_image, style:"display:none", class: "uploader" %>
          <%= f.hidden_field :post_image_cache %>
        <% end %>
        </div>
        <div class="content">
          <p><%= f.text_field :title, placeholder: "コーデタイトル", class: "form-text" %></p>
          <p><%= f.text_area :introduction, placeholder: text_placeholder, size: '15x7', class: "form-area" %></p>
          <p><%= f.select :category,
          [["basic(ベーシック)", "basic"],
          ["colorful(カラフル)", "colorful"],
          ["feminine(フェミニン)", "feminine"],
          ["sneaker(スニーカースタイル)", "sneaker"],
          ["stylish(スタイリッシュ)", "stylish"]],
          {include_blank: "カテゴリー選択（任意）"}, {id: 'select'} %></p>
          <p><%= f.submit "確認画面へ", class:"form-btn" %></p>
        </div>
      </div>
    <% end %>
  </div
</div>

app/views/posts/search.html.erb
<div class="index-container">
  <p class="title">検索結果：<%= @posts.count %>件</p>
  <div class="index-content">
    <% @posts.each do |post| %>
      <div class="index-items">
        <p><%= post.title %></p>
        <p><%= image_tag post.post_image.url, class: "index-image" %></p>
        <div class="index-nav">
          <div class="index-user">
            <% if post.user.avatar? %>
              <p><%= image_tag post.user.avatar.url, size: '50x50', class: "index-icon" %></p>
            <% else %>
              <%= image_tag 'icon_dummy.png', size: '50x50', class:"index-icon" %>
            <% end %>
            <p class="user-name"><%= post.user.name %></p>
          </div>
          <%= link_to "詳しく見る", post_path(post), class: "show-link" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/stylish.html.erb
<div class="index-container">
  <p class="title">スタイリッシュ</p>
  <div class="index-content">
  <% @posts.each do |post| %>
    <div class="index-items">
      <p><%= post.title %></p>
      <p><%= image_tag post.post_image.url, class: "index-image" %></p>
      <div class="index-nav">
        <div class="index-user">
          <% if post.user.avatar? %>
            <p><%= image_tag post.user.avatar.url, size: '50x50', class: "index-icon" %></p>
          <% else %>
            <%= image_tag 'icon_dummy.png', size: '50x50', class:"index-icon" %>
          <% end %>
          <p class="user-name"><%= post.user.name %></p>
        </div>
        <%= link_to "more", post_path(post), class: "show-link" %>
      </div>
    </div>
  <% end %>
  <%= paginate(@posts) %>
</div>
</div>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>