config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'
  get 'comments/destroy'
  get 'relationships/followings'
  get 'relationships/followers'
  root to: 'home#top'
  resources :posts do
    resources :comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
    member do
      get :favorites_all
    end
    collection do
      post :confirm
      get :draft
      get :index_all
      get :all_posts
      get 'search' => 'posts#search'
      get 'basic' => 'posts#basic'
      get 'stylish' => 'posts#stylish'
      get 'feminine' => 'posts#feminine'
      get 'sneaker' => 'posts#sneaker'
      get 'colorful' => 'posts#colorful'
    end
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
  end
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
end

app/views/layouts/_footer.html.erb
<footer>
  <%= image_tag "footer-logo.png", class:"footer-logo" %>
  <p>© 2022 Feesly, Inc.</p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="nav">
    <%= link_to root_path, id: 'logo' do %>
      <% image_tag 'logo.png', class: "nav__logo" %>
    <% end %>
    <%= form_with url: search_posts_path, method: :get, local: true do |f| %>
      <%= f.text_field :keyword, placeholder:"キーワード検索", class: "search" %>
      <% f.submit :keyword %>
    <% end %>
    <div class="nav__btn">
      <% if user_signed_in? %>
        <div class="nav__icon">
          <% if current_user.avatar? %>
            <%= image_tag current_user.avatar.url, size: '50x50', class:"icon" %>
          <% else %>
            <%= image_tag 'icon_dummy.png', size: '50x50', class:"icon" %>
          <% end %>
        </div>
        <% if current_page?(new_post_path) %>
          <%= link_to "戻る", root_path, class:"new_post" %>
        <% else %>
          <%= link_to "投稿", new_post_path, class:"new_post" %>
        <% end %>
        <div class="hamburger-menu">
          <%= image_tag 'open-menu.png', size: '40x40', id: "open-menu.png" %>
        </div>
        <div class="menu-list">
          <div class="menu-item">
            <ul>
              <li>ログイン中のアカウント：<br><%= current_user.name %></li>
              <li>
                <%= link_to user_followings_path(current_user), class:"link" do %>
                  <p>フォロー <%= current_user.followings.count %></p>
                <% end %>
                <%= link_to user_followers_path(current_user), class:"link" do %>
                  <p>フォロワー <%= current_user.followers.count %></p>
                <% end %>
              </li>
              <li><%= link_to "自分の投稿", posts_path, class:"link" %></li>
              <li><%= link_to "下書き一覧", draft_posts_path, class:"link" %></li>
              <li><%= link_to "みんなの投稿", index_all_posts_path, class:"link" %></li>
              <li><%= link_to "いいねした投稿", favorites_all_post_path(current_user), class:"link" %></li>
              <li></li>
              <li><%= link_to "アカウント設定", edit_user_registration_path, class:"link" %></li>
              <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"link" %></li>
            </ul>
            <%= image_tag 'close-menu.png', class:"menu_close", size: '40x40' %>
          </div>
        </div>
        <div class="overlay"></div>
      <% else %>
        <div class="login-hamburger-menu">
          <%= image_tag 'open-menu.png', size: '40x40', id: "login-open" %>
        </div>
        <div class="login-list">
          <div class="login-nav">
            <%= image_tag 'close-menu.png', class:"login-close", size: '40x40' %>
            <%= link_to "ゲストログイン", users_guest_sign_in_path, method: :post, class: 'post' %>
            <%= link_to "ログイン", new_user_session_path, class: 'post' %>
            <%= link_to "新規登録", new_user_registration_path, class: 'post' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ASHIMOTO App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1, maximum-scale=1.0, minimum-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <p class="alert"><%= alert %></p>
    <% if flash.notice %>
    <p class="notice"><%= notice %></p>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>